import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'

import Link from 'next/link'
import Navbar from '@/component/Header/Navbar'
import Footer from '@/component/Footer/Footer'
import React, { useState, useEffect } from 'react';



const inter = Inter({ subsets: ['latin'] })

export default function Home() {

	const [textIndex, setTextIndex] = useState(0); // Initialize state for text index with initial value 0
	const texts = ['Developer', 'Freelancer', 'Blogger']; // Array of texts to display
	const intervals = [3000, 5000, 2000, 4000]; // Array of time intervals in milliseconds for each text

	useEffect(() => {
		// Function to update text index dynamically at regular intervals
		const interval = setInterval(() => {
		  setTextIndex((prevIndex) => (prevIndex + 1) % texts.length); // Update text index to next value in array
		}, intervals[textIndex]); // Use time interval corresponding to current text index
	
		return () => {
		  clearInterval(interval); // Clean up interval on component unmount
		};
	  }, [textIndex]);
  return (
    <>
      <Head>
        <title>Bhuvaneshwaran -👋,Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href='' />
	
      </Head>
    <main>
  <Navbar/>


 

<section>
	<div className="dark:bg-violet-400">
	<div className="grid gap-4 sm:grid-cols-1 sm:pr-8 xl:grid-cols-2 md:grid-cols-2 lg:grid-cols-2 2xl:grid-cols-2">
		<div className="pt-10">
			<h1 className='text-3xl text-center text-green-400 md:text-left md:pl-16 lg:text-left xl:pl-28'>Welcome</h1>
			<h5 className='pt-10 text-5xl text-center pl-14 lg:text-left md:pr-2 xl:pl-28'><p className='font-bold text-green-400'>
				<span className='text-4xl text-black '>I am </span><span className='text-4xl'> {texts[textIndex]} </span>  </p></h5>
			


			
		</div>
		<div>
			{/* <div className='grid w-full bg-green-400 grid-row-2'>
				<div>01</div>
				<div>02</div>
			</div> */}

			
			
		</div>
	
	</div>


	</div>
	{/* <Image src="/Get-touch.svg" width={500} height={200} alt="" className="w-5/6 mx-auto mb-12 -mt-20 rounded-lg shadow-md lg:-mt-40 dark:bg-gray-500" /> */}
</section>

	<div className="px-4 py-16 mx-auto text-xl sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8 lg:py-20 dark:bg-gray-800 dark:text-gray-100">
	<h2 className="mb-8 font-bold leading-none text-center text-green-400 sm:text-xs lg:text-4xl md:text-3xl ">How can I add value to your team and organization</h2>
	<h1 className="text-justify sm:mx-auto sm:leading-2 lg:text-xl md:text-md md:leading-7">I have a passion for creating elegant and efficient solutions to complex problems. I am experienced in a 
	range of programming languages and frameworks, and have worked on projects across a variety of industries.
	I bring a strong combination of technical expertise and problem-solving skills to the table, which enables me to quickly identify areas for improvement and develop
	 effective solutions. I am a proactive communicator who enjoys working collaboratively with cross-functional teams to achieve shared goals.
	I am committed to staying up-to-date with the latest trends and best practices in the industry, and have a track record of delivering high-quality work on time 
	and within budget. Whether{"it's"}  developing new applications, improving existing systems, or solving complex technical challenges, I am always eager to take on 
	new challenges and contribute to the success of the team.</h1>
	<ul className="grid gap-3 pt-5 md:grid-cols-2 lg:grid-cols-3">
		<li className="flex items-center space-x-2">
			<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" className="w-5 h-5 fill-current dark:text-violet-400">
				<path d="M426.072,86.928A238.75,238.75,0,0,0,88.428,424.572,238.75,238.75,0,0,0,426.072,86.928ZM257.25,462.5c-114,0-206.75-92.748-206.75-206.75S143.248,49,257.25,49,464,141.748,464,255.75,371.252,462.5,257.25,462.5Z"></path>
				<polygon points="221.27 305.808 147.857 232.396 125.23 255.023 221.27 351.063 388.77 183.564 366.142 160.937 221.27 305.808"></polygon>
			</svg>
			<span>Technical expertise</span>
		</li>
		<li className="flex items-center space-x-2">
			<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" className="w-5 h-5 fill-current dark:text-violet-400">
				<path d="M426.072,86.928A238.75,238.75,0,0,0,88.428,424.572,238.75,238.75,0,0,0,426.072,86.928ZM257.25,462.5c-114,0-206.75-92.748-206.75-206.75S143.248,49,257.25,49,464,141.748,464,255.75,371.252,462.5,257.25,462.5Z"></path>
				<polygon points="221.27 305.808 147.857 232.396 125.23 255.023 221.27 351.063 388.77 183.564 366.142 160.937 221.27 305.808"></polygon>
			</svg>
			<span>Problem-solving skills </span>
		</li>
		<li className="flex items-center space-x-2">
			<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" className="w-5 h-5 fill-current dark:text-violet-400">
				<path d="M426.072,86.928A238.75,238.75,0,0,0,88.428,424.572,238.75,238.75,0,0,0,426.072,86.928ZM257.25,462.5c-114,0-206.75-92.748-206.75-206.75S143.248,49,257.25,49,464,141.748,464,255.75,371.252,462.5,257.25,462.5Z"></path>
				<polygon points="221.27 305.808 147.857 232.396 125.23 255.023 221.27 351.063 388.77 183.564 366.142 160.937 221.27 305.808"></polygon>
			</svg>
			<span>Adaptability</span>
		</li>
		<li className="flex items-center space-x-2">
			<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" className="w-5 h-5 fill-current dark:text-violet-400">
				<path d="M426.072,86.928A238.75,238.75,0,0,0,88.428,424.572,238.75,238.75,0,0,0,426.072,86.928ZM257.25,462.5c-114,0-206.75-92.748-206.75-206.75S143.248,49,257.25,49,464,141.748,464,255.75,371.252,462.5,257.25,462.5Z"></path>
				<polygon points="221.27 305.808 147.857 232.396 125.23 255.023 221.27 351.063 388.77 183.564 366.142 160.937 221.27 305.808"></polygon>
			</svg>
			<span>Attention to detail</span>
		</li>
		<li className="flex items-center space-x-2">
			<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" className="w-5 h-5 fill-current dark:text-violet-400">
				<path d="M426.072,86.928A238.75,238.75,0,0,0,88.428,424.572,238.75,238.75,0,0,0,426.072,86.928ZM257.25,462.5c-114,0-206.75-92.748-206.75-206.75S143.248,49,257.25,49,464,141.748,464,255.75,371.252,462.5,257.25,462.5Z"></path>
				<polygon points="221.27 305.808 147.857 232.396 125.23 255.023 221.27 351.063 388.77 183.564 366.142 160.937 221.27 305.808"></polygon>
			</svg>
			<span>Passion for development</span>
		</li>
		<li className="flex items-center space-x-2">
			<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" className="w-5 h-5 fill-current dark:text-violet-400 ">
				<path d="M426.072,86.928A238.75,238.75,0,0,0,88.428,424.572,238.75,238.75,0,0,0,426.072,86.928ZM257.25,462.5c-114,0-206.75-92.748-206.75-206.75S143.248,49,257.25,49,464,141.748,464,255.75,371.252,462.5,257.25,462.5Z"></path>
				<polygon points="221.27 305.808 147.857 232.396 125.23 255.023 221.27 351.063 388.77 183.564 366.142 160.937 221.27 305.808"></polygon>
			</svg>
			<span>Results-oriented </span>
		</li>
	</ul>
</div>

{/* <section className="p-6 dark:text-gray-100">
	<form novalidate="" className="container w-full max-w-xl p-8 mx-auto space-y-6 rounded-md shadow dark:bg-gray-900 ng-untouched ng-pristine ng-valid">
		<h2 className="w-full text-3xl font-bold leading-tight text-green-400">Contact</h2>
		
		<div>
				Email: <span>
			bhuvaneshwaran368@gmail.com
        
      </span>
			</div>
		<h1 className='w-full text-2xl text-green-400'>Get in contact with me</h1>
		<div>
			<label for="name" className="block mb-1 ml-1 text-green-400 text-{10}">Name</label>
			<input id="name" type="text" placeholder="Your name" required="" className="block w-full p-2 rounded focus:outline-none focus:ring focus:ring-opacity-25 focus:ring-green-400 dark:bg-gray-800" />
		</div>
		<div>
			<label for="email" className="block mb-1 ml-1 text-green-400 text-{10}">Email</label>
			<input id="email" type="email" placeholder="Your email" required="" className="block w-full p-2 rounded focus:outline-none focus:ring focus:ring-opacity-25 focus:ring-green-400 dark:bg-gray-800" />
		</div>
		<div>
			<label for="message" className="block mb-1 ml-1 text-green-400 text-{10}">Message</label>
			<textarea id="message" type="text" placeholder="Message..." className="block w-full p-2 rounded autoexpand focus:outline-none focus:ring focus:ring-opacity-25 focus:ring-green-400 dark:bg-gray-800"></textarea>
		</div>
		<div>
			<button type="submit" className="w-full px-4 py-2 font-bold text-white bg-green-400 rounded shadow focus:outline-none focus:ring hover:ring focus:ring-opacity-50 dark:bg-white focus:ring-green-400 dark:text-gray-900">Send</button>
		</div>
	</form>
</section> */}




    </main>
	<Footer/>
    </>
  )
}
